### PR TITLE
Fixed Unrecognized resource type [litecoin_address, ethereum_address, bitcoin_cash_address, litecoin_network, ethereum_network, bitcoin_cash_network] 

### PR DESCRIPTION
**Pull request by shked0wn**
I added the type to the Mapper in order to create an address following previous method

#137

### CODE REVIEW

**Comment by ymschaap** [comment]
Yes, would love to see this merged.

**Comment by shked0wn** [comment]
Since I opened my merge request I also added fix to following missing ressources : 
- ethereum_address
- bitcoin_cash_network
- bitcoin_cash_address
- litecoin_network

More to come surely, I will add it when bugs will occurs.

**Comment by ymschaap** [comment]
Yes, given we are working on the same thing, the following is missing as well:
* ethereum_network

**Comment by incify** [comment]
You may forgot to add 

> use Coinbase\Wallet\Resource\EthereumNetwork;
to Mapper

**Comment by xCette** [comment]
I too would like to see this merged. :)

**Comment by shked0wn** [comment]
@xCette You are welcome ;)

**Comment by shked0wn** [comment]
I made a tweet to Coinbase to try to get someone that can merge this, if you want to RT : https://twitter.com/floranpagliai/status/950314893697220610

**Comment by MasterCassim** [comment]
+1

**Comment by sds** [comment]
Apologies for the silence here, @shked0wn.

I've gone through and merged a number of old PRs, which seems to have caused conflicts with this one. Can you rebase and tag me when it's ready for review? Happy to merge in that case. 

Thanks!

**Comment by shked0wn** [comment]
Hello @sds, I have rebased the PR, it's ready to be reviewed. Happy to help ;)

**Pull request merged**
